version: "3.8"

services:
  mysqldb:
    image: mysql:8.1.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db_docker
      MYSQL_USER: sonkq
      MYSQL_PASSWORD: sonkq09
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3307:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
